### ISSUE TITLE
Remove `status` from all test objects once HTTPProxy is updated

### ISSUE THREAD

**Issue by youngnick** [projectcontour/ir2proxy#9]
Once HTTPProxy is updated (in https://github.com/projectcontour/contour/issues/1973), then all the test HTTPProxy YAMLs will need to have the `status` stanza removed.

**Comment by moderation** [comment]
The empty `status: {}` stanza at the end of a converted IngressRoute object causes the following deployment failures in our environment:

```
error: error validating "kube\\kustomize\\overlays\\local": error validating data: [ValidationError(HTTPProxy.status): missing required field "currentStatus" in io.projectcontour.v1.HTTPProxy.status, ValidationError(HTTPProxy.status): missing required field "description" in io.projectcontour.v1.HTTPProxy.status]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by davecheney** [comment]
@youngnick I was _sure_ we specifically added code to remove that turd. Do you know what’s going on here?

On 25 Feb 2020, at 08:01, moderation <notifications@github.com> wrote:

﻿

The empty status: {} stanza at the end of a converted IngressRoute object causes the following deployment failures in our environment:

error: error validating "kube\\kustomize\\overlays\\local": error validating data: [ValidationError(HTTPProxy.status): missing required field "currentStatus" in io.projectcontour.v1.HTTPProxy.status, ValidationError(HTTPProxy.status): missing required field "description" in io.projectcontour.v1.HTTPProxy.status]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by davecheney** [comment]
> The empty `status: {}` stanza at the end of a converted IngressRoute object causes the following deployment failures in our environment:
> 
> ```
> error: error validating "kube\\kustomize\\overlays\\local": error validating data: [ValidationError(HTTPProxy.status): missing required field "currentStatus" in io.projectcontour.v1.HTTPProxy.status, ValidationError(HTTPProxy.status): missing required field "description" in io.projectcontour.v1.HTTPProxy.status]; if you choose to ignore these errors, turn validation off with --validate=false
> ```

@moderation sorry I didn’t realise this was a pr, can you please log an issue and we’ll investigate.
